service: soundcloud-web-scraper
custom:
  secrets: ${file(secrets.json)}
provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-2
  environment: 
    EMAIL_ADDRESS: ${self:custom.secrets.EMAIL_ADDRESS}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "ses:SendEmail"
        - "ses:SendRawEmail"
      Resource: "*"
functions:
  emailOnNewUpload:
    handler: handler.emailOnNewUpload
    events:
      - schedule: cron(0 12 * * ? *)
